#! /usr/bin/env bash

# This script resizes an image file preserving it's aspect ratio.
# Pass the filename the image when calling the script: imageResize image-name.jpg
# When prompted enter the desired width and the image will be resized.

echo "What is the width you woud like to resize the image to?"
read -r width

convert $1 -resize $width converted.$1

resized="$(identify -format "%wx%h" converted.$1)"

echo "The image is now $resized"
